# Generated by Django 3.2 on 2022-02-26 14:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('answer', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Instructions', max_length=25)),
                ('instructions', ckeditor.fields.RichTextField(default='Put your instructions here')),
                ('footer', models.CharField(default='© 2022 Regnabytes Ltd', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('', '--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, unique=True)),
                ('answer_category', models.CharField(choices=[('', '--'), ('boolean', 'True / False'), ('likert6', '6 point Likert'), ('likert7', '7 point Likert'), ('brake1', '1 min brake'), ('brake2', '2 min brake'), ('brake5', '5 min brake'), ('brake10', '10 min brake'), ('brake15', '15 min brake')], default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('gender', models.CharField(choices=[('', '--'), ('M', 'Άρρεν / Male'), ('F', 'Θήλυ / Female')], default='', max_length=1)),
                ('age', models.CharField(choices=[('', '--'), ('u17', 'u17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56-64', '56-64'), ('65+', '65+')], default='', max_length=5)),
                ('education', models.CharField(choices=[('', '--'), ('gymnasium', 'Γυμνάσιο / Gymnasium'), ('lyceum', 'Λύκειο - Τεχνική Σχολή / Lyceum'), ('BSc', 'Πτυχίο / Bachelor'), ('MSc', "Μεταπτυχιακό / Master's"), ('PhD', 'Διδακτορικό / Doctorate')], default='', max_length=10)),
                ('district', models.CharField(choices=[('', '--'), ('lemesos', 'Λεμεσός/ Λεμεσός'), ('nicosia', 'Λευκωσία / Nicosia'), ('larnaca', 'Λάρνακα / Larnaca'), ('paphos', 'Πάφος / Paphos'), ('ammochostos', 'Αμμόχωστος / Ammochostos'), ('kyrenia', 'Κερύνεια / Kyrenia')], default='', max_length=12)),
                ('residence', models.CharField(choices=[('', '--'), ('city', 'Πόλη / City'), ('suburb', 'Προάστιο / Suburb'), ('village', 'Χωριό / Village')], default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(max_length=1500)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.section')),
            ],
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='MyOption',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.option',),
        ),
        migrations.CreateModel(
            name='MyQuestion',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.question',),
        ),
        migrations.CreateModel(
            name='MySection',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.question',),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.user',),
        ),
    ]
