# Generated by Django 2.2.10 on 2020-04-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('timestamp', models.CharField(max_length=120)),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('file_name', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_count', models.PositiveSmallIntegerField(default=15)),
                ('countdown_per_pic', models.PositiveSmallIntegerField(default=60)),
                ('language', models.CharField(choices=[('EL', 'EL'), ('EN', 'EN')], default='EL', max_length=2)),
                ('headline_el', models.CharField(default='Οδηγίες', max_length=25)),
                ('headline_en', models.CharField(default='Instructions', max_length=25)),
                ('instructions_el', models.TextField(default='Χώρος εισαγωγής οδηγιών/πληροφοριών.')),
                ('instructions_en', models.TextField(default='Put your instructions here')),
                ('footer_el', models.CharField(default='© 2020 Περικλής Περικλέους - Πανεπιστήμιο Πατρών: Τμήμα Ηλεκτρολόγων Μηχανικών & Τεχνολογίας Υπολογιστών', max_length=120)),
                ('footer_en', models.CharField(default='© 2020 Periklis Perikleous - University of Patras: Department of Eletrical & Computer Engineering', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_location', models.ImageField(upload_to='')),
                ('caption_el', models.CharField(blank=True, max_length=100)),
                ('caption_en', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Primary pictures',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.FloatField(verbose_name='x - left')),
                ('top', models.FloatField(verbose_name='y - top')),
                ('width', models.FloatField(verbose_name='Dx - width')),
                ('height', models.FloatField(verbose_name='Dy - height')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target', to='pages.Primary')),
            ],
        ),
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_location', models.ImageField(upload_to='')),
                ('caption_el', models.CharField(blank=True, max_length=100)),
                ('caption_en', models.CharField(blank=True, max_length=100)),
                ('description_el', models.CharField(blank=True, max_length=500)),
                ('description_en', models.CharField(blank=True, max_length=500)),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Secondary', to='pages.Primary')),
            ],
            options={
                'verbose_name_plural': 'Secondary pictures',
            },
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='MyPrimary',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ 1 ~ Import/Export Primary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.primary',),
        ),
        migrations.CreateModel(
            name='MySecondary',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ 2 ~ Import/Export Secondary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.secondary',),
        ),
        migrations.CreateModel(
            name='MyTarget',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ 3 ~ Import/Export Targets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.target',),
        ),
    ]
