# Generated by Django 3.2 on 2022-02-19 14:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('answer', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Instructions', max_length=25)),
                ('instructions', ckeditor.fields.RichTextField(default='Put your instructions here')),
                ('footer', models.CharField(default='© 2022 Regnabytes Ltd', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(max_length=500)),
                ('answer_category', models.CharField(choices=[('boolean', 'True / False'), ('likert6', '6 point Likert'), ('likert7', '7 point Likert')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('gender', models.CharField(choices=[('', '---'), ('M', 'Άρρεν / Male'), ('F', 'Θήλυ / Female')], max_length=1)),
                ('age', models.CharField(choices=[('', '---'), ('u17', '-17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-54', '46-54'), ('55-64', '55-64'), ('65+', '65+')], max_length=5)),
                ('education', models.CharField(choices=[('', '---'), ('gymnasium', 'Γυμνάσιο / Gymnasium'), ('lyceum', 'Λύκειο - Τεχνική Σχολή / Lyceum'), ('BSc', 'Πτυχίο / Bachelor'), ('MSc', "Μεταπτυχιακό / Master's"), ('PhD', 'Διδακτορικό / Doctorate')], max_length=30)),
                ('district', models.CharField(choices=[('', '---'), ('lemesos', 'Λεμεσός/ Λεμεσός'), ('nicosia', 'Λευκωσία / Nicosia'), ('larnaca', 'Λάρνακα / Larnaca'), ('paphos', 'Πάφος / Paphos'), ('ammochostos', 'Αμμόχωστος / Ammochostos'), ('kyrenia', 'Κερύνεια / Kyrenia')], max_length=30)),
                ('residence', models.CharField(choices=[('', '---'), ('city', 'Πόλη / City'), ('suburb', 'Προάστιο / Suburb'), ('village', 'Χωριό / Village')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='MyOption',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.option',),
        ),
        migrations.CreateModel(
            name='MyQuestion',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.question',),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.user',),
        ),
    ]
