# Generated by Django 3.0.5 on 2020-04-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primary',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primary',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secondary',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secondary',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='primary',
            name='image_location',
            field=models.ImageField(height_field='height_field', upload_to='', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='image_location',
            field=models.ImageField(height_field='height_field', upload_to='', width_field='width_field'),
        ),
    ]
