# Generated by Django 3.0.5 on 2020-04-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200418_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='footer_el',
            field=models.CharField(default='© 2020 Περικλής Περικλέους - Πανεπιστήμιο Πατρών', max_length=120),
        ),
        migrations.AlterField(
            model_name='option',
            name='footer_en',
            field=models.CharField(default='© 2020 Periklis Perikleous - University of Patras', max_length=120),
        ),
    ]
