# Generated by Django 3.0.5 on 2020-04-18 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200418_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_pri_el', models.CharField(blank=True, max_length=100)),
                ('caption_pri_en', models.CharField(blank=True, max_length=100)),
                ('caption_sec_el', models.CharField(blank=True, max_length=100)),
                ('caption_sec_en', models.CharField(blank=True, max_length=100)),
                ('description_el', models.CharField(blank=True, max_length=500)),
                ('description_en', models.CharField(blank=True, max_length=500)),
                ('image_pri', models.ImageField(height_field='height_pri', upload_to='', width_field='width_pri')),
                ('height_pri', models.IntegerField(default=0)),
                ('width_pri', models.IntegerField(default=0)),
                ('image_sec', models.ImageField(height_field='height_sec', upload_to='', width_field='width_sec')),
                ('height_sec', models.IntegerField(default=0)),
                ('width_sec', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pairs',
            },
        ),
        migrations.RemoveField(
            model_name='secondary',
            name='primary',
        ),
        migrations.DeleteModel(
            name='MyPrimary',
        ),
        migrations.DeleteModel(
            name='MySecondary',
        ),
        migrations.RemoveField(
            model_name='target',
            name='height',
        ),
        migrations.RemoveField(
            model_name='target',
            name='left',
        ),
        migrations.RemoveField(
            model_name='target',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='target',
            name='top',
        ),
        migrations.RemoveField(
            model_name='target',
            name='width',
        ),
        migrations.AddField(
            model_name='target',
            name='x_pri',
            field=models.FloatField(null=True, verbose_name='x - primary'),
        ),
        migrations.AddField(
            model_name='target',
            name='x_sec',
            field=models.FloatField(null=True, verbose_name='x - secondary'),
        ),
        migrations.AddField(
            model_name='target',
            name='y_pri',
            field=models.FloatField(null=True, verbose_name='y - primary'),
        ),
        migrations.AddField(
            model_name='target',
            name='y_sec',
            field=models.FloatField(null=True, verbose_name='y - secondary'),
        ),
        migrations.DeleteModel(
            name='Primary',
        ),
        migrations.DeleteModel(
            name='Secondary',
        ),
        migrations.CreateModel(
            name='MyPair',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ 2 ~ Import/Export Pair',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.pair',),
        ),
        migrations.AddField(
            model_name='target',
            name='pair',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='pages.Pair'),
        ),
    ]
