# Generated by Django 3.2 on 2022-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_user_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(choices=[('', '--'), ('lemesos', 'Λεμεσός / Lemesos'), ('nicosia', 'Λευκωσία / Nicosia'), ('larnaca', 'Λάρνακα / Larnaca'), ('paphos', 'Πάφος / Paphos'), ('ammochostos', 'Αμμόχωστος / Ammochostos'), ('kyrenia', 'Κερύνεια / Kyrenia')], default='', max_length=12),
        ),
    ]
