# Generated by Django 3.2 on 2022-03-04 15:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_user_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='answer',
        ),
        migrations.AddField(
            model_name='data',
            name='question',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='selection',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='team',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
