# Generated by Django 3.0.5 on 2020-04-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200419_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='pair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='pages.Pair'),
        ),
        migrations.AlterField(
            model_name='target',
            name='x_pri',
            field=models.FloatField(verbose_name='x - primary'),
        ),
        migrations.AlterField(
            model_name='target',
            name='x_sec',
            field=models.FloatField(verbose_name='x - secondary'),
        ),
        migrations.AlterField(
            model_name='target',
            name='y_pri',
            field=models.FloatField(verbose_name='y - primary'),
        ),
        migrations.AlterField(
            model_name='target',
            name='y_sec',
            field=models.FloatField(verbose_name='y - secondary'),
        ),
    ]
