# Generated by Django 3.0.5 on 2020-04-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200419_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='description_el',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pair',
            name='description_en',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
