# Generated by Django 3.0.5 on 2020-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200420_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='description_el',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='description_en',
            field=models.TextField(blank=True),
        ),
    ]
