# Generated by Django 3.2 on 2022-02-20 10:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20220219_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_category',
            field=models.CharField(choices=[('', '--'), ('boolean', 'True / False'), ('likert6', '6 point Likert'), ('likert7', '7 point Likert')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor.fields.RichTextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(choices=[('', '--'), ('u17', 'u17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56-64', '56-64'), ('65+', '65+')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(choices=[('', '--'), ('lemesos', 'Λεμεσός/ Λεμεσός'), ('nicosia', 'Λευκωσία / Nicosia'), ('larnaca', 'Λάρνακα / Larnaca'), ('paphos', 'Πάφος / Paphos'), ('ammochostos', 'Αμμόχωστος / Ammochostos'), ('kyrenia', 'Κερύνεια / Kyrenia')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('', '--'), ('gymnasium', 'Γυμνάσιο / Gymnasium'), ('lyceum', 'Λύκειο - Τεχνική Σχολή / Lyceum'), ('BSc', 'Πτυχίο / Bachelor'), ('MSc', "Μεταπτυχιακό / Master's"), ('PhD', 'Διδακτορικό / Doctorate')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence',
            field=models.CharField(choices=[('', '--'), ('city', 'Πόλη / City'), ('suburb', 'Προάστιο / Suburb'), ('village', 'Χωριό / Village')], default='', max_length=12),
        ),
    ]
