# Generated by Django 3.0.5 on 2020-04-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200420_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypair',
            options={'verbose_name_plural': '~ Import/Export Pairs'},
        ),
        migrations.AlterModelOptions(
            name='mytarget',
            options={'verbose_name_plural': '~ Import/Export Targets'},
        ),
        migrations.AddField(
            model_name='target',
            name='h_pri',
            field=models.FloatField(default=0, verbose_name='height - primary'),
        ),
        migrations.AddField(
            model_name='target',
            name='h_sec',
            field=models.FloatField(default=0, verbose_name='height - secondary'),
        ),
        migrations.AddField(
            model_name='target',
            name='w_pri',
            field=models.FloatField(default=0, verbose_name='width - primary'),
        ),
        migrations.AddField(
            model_name='target',
            name='w_sec',
            field=models.FloatField(default=0, verbose_name='width - secondary'),
        ),
    ]
