# Generated by Django 3.0.5 on 2020-04-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200429_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='height_pri',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='height_sec',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='width_pri',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='width_sec',
        ),
        migrations.AlterField(
            model_name='pair',
            name='image_pri',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='pair',
            name='image_sec',
            field=models.ImageField(upload_to=''),
        ),
    ]
