# Generated by Django 3.2 on 2022-02-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_question_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('', '--'), ('a', 'A'), ('b', 'B')], default='', max_length=1),
        ),
    ]
