# Generated by Django 3.0.5 on 2020-04-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200430_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='height_pri',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pair',
            name='height_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pair',
            name='width_pri',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pair',
            name='width_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pair',
            name='image_pri',
            field=models.ImageField(height_field='height_pri', upload_to='', width_field='width_pri'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='image_sec',
            field=models.ImageField(height_field='height_sec', upload_to='', width_field='width_sec'),
        ),
    ]
