# Generated by Django 3.0.5 on 2020-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200430_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
