# Generated by Django 3.0.5 on 2020-04-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200430_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='h_sec',
            field=models.FloatField(verbose_name='height - secondary'),
        ),
        migrations.AlterField(
            model_name='target',
            name='w_sec',
            field=models.FloatField(verbose_name='width - secondary'),
        ),
        migrations.AlterField(
            model_name='target',
            name='x_sec',
            field=models.FloatField(verbose_name='x - secondary'),
        ),
        migrations.AlterField(
            model_name='target',
            name='y_sec',
            field=models.FloatField(verbose_name='y - secondary'),
        ),
    ]
