# Generated by Django 3.0.6 on 2020-05-09 17:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200509_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='instructions_el',
            field=ckeditor.fields.RichTextField(default='Χώρος εισαγωγής οδηγιών/πληροφοριών.'),
        ),
        migrations.AlterField(
            model_name='option',
            name='instructions_en',
            field=ckeditor.fields.RichTextField(default='Put your instructions here'),
        ),
    ]
