# Generated by Django 3.0.6 on 2020-05-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20200512_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='caption_pri_el',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pair',
            name='caption_pri_en',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pair',
            name='caption_sec_el',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pair',
            name='caption_sec_en',
            field=models.CharField(max_length=50),
        ),
    ]
