# Generated by Django 3.0.6 on 2020-05-15 12:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200512_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='caption_pri_el',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pair',
            name='caption_pri_en',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pair',
            name='caption_sec_el',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pair',
            name='caption_sec_en',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pair',
            name='description_el',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
