# Generated by Django 3.0.6 on 2020-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200515_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='x',
            new_name='xbr',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='y',
            new_name='xtl',
        ),
        migrations.AddField(
            model_name='data',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ybr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ytl',
            field=models.FloatField(null=True),
        ),
    ]
