# Generated by Django 3.0.6 on 2020-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20200515_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='xbr',
            new_name='xbr_pri',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='xtl',
            new_name='xbr_sec',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='ybr',
            new_name='xtl_pri',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='ytl',
            new_name='xtl_sec',
        ),
        migrations.AddField(
            model_name='data',
            name='ybr_pri',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ybr_sec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ytl_pri',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ytl_sec',
            field=models.FloatField(null=True),
        ),
    ]
