# Generated by Django 3.0.6 on 2020-05-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20200515_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='MyData',
        ),
    ]
