# Generated by Django 3.0.6 on 2020-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20200523_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.FloatField(null=True)),
                ('pair_id', models.CharField(max_length=40)),
                ('file_name_pri', models.CharField(blank=True, max_length=120, null=True)),
                ('file_name_sec', models.CharField(blank=True, max_length=120, null=True)),
                ('xtl_pri', models.FloatField(null=True)),
                ('ytl_pri', models.FloatField(null=True)),
                ('xbr_pri', models.FloatField(null=True)),
                ('ybr_pri', models.FloatField(null=True)),
                ('xtl_sec', models.FloatField(null=True)),
                ('ytl_sec', models.FloatField(null=True)),
                ('xbr_sec', models.FloatField(null=True)),
                ('ybr_sec', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
    ]
