# Generated by Django 3.0.6 on 2020-05-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_data_mydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='file_name_pri',
            new_name='filename_pri',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='file_name_sec',
            new_name='filename_sec',
        ),
    ]
