# Generated by Django 3.0.6 on 2020-05-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20200523_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='MyData',
        ),
    ]
