# Generated by Django 3.0.6 on 2020-05-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200524_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.FloatField(null=True)),
                ('filename_pri', models.CharField(blank=True, max_length=120, null=True)),
                ('filename_sec', models.CharField(blank=True, max_length=120, null=True)),
                ('xtl_pri', models.FloatField(null=True)),
                ('ytl_pri', models.FloatField(null=True)),
                ('xbr_pri', models.FloatField(null=True)),
                ('ybr_pri', models.FloatField(null=True)),
                ('xtl_sec', models.FloatField(null=True)),
                ('ytl_sec', models.FloatField(null=True)),
                ('xbr_sec', models.FloatField(null=True)),
                ('ybr_sec', models.FloatField(null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_id', to='pages.Pair')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
    ]
