# Generated by Django 3.0.6 on 2020-05-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_data_mydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_id', to='pages.Pair'),
        ),
    ]
