# Generated by Django 3.0.6 on 2020-05-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20200524_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('total_score', models.FloatField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('response', models.FloatField(null=True)),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Pair')),
            ],
            options={
                'verbose_name_plural': 'Rank',
            },
        ),
    ]
