# Generated by Django 3.0.6 on 2020-05-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRank',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Rank',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
    ]
