# Generated by Django 3.0.6 on 2020-05-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_myrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='pair',
            field=models.IntegerField(),
        ),
    ]
