# Generated by Django 3.0.6 on 2020-05-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20200531_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='MyRank',
        ),
    ]
