# Generated by Django 3.0.6 on 2020-05-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20200531_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.IntegerField()),
                ('session', models.IntegerField()),
                ('total_score', models.FloatField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('response', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Rank',
            },
        ),
        migrations.CreateModel(
            name='MyRank',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Rank',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
    ]
