# Generated by Django 3.0.6 on 2020-05-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20200531_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='pair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pair_target', to='pages.Pair'),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('total_score', models.FloatField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('response', models.FloatField(null=True)),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_rank', to='pages.Pair')),
            ],
            options={
                'verbose_name_plural': 'Rank',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.FloatField(null=True)),
                ('filename_pri', models.CharField(blank=True, max_length=120, null=True)),
                ('filename_sec', models.CharField(blank=True, max_length=120, null=True)),
                ('xtl_pri', models.FloatField(null=True)),
                ('ytl_pri', models.FloatField(null=True)),
                ('xbr_pri', models.FloatField(null=True)),
                ('ybr_pri', models.FloatField(null=True)),
                ('xtl_sec', models.FloatField(null=True)),
                ('ytl_sec', models.FloatField(null=True)),
                ('xbr_sec', models.FloatField(null=True)),
                ('ybr_sec', models.FloatField(null=True)),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_data', to='pages.Pair')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='MyRank',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Rank',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
    ]
