# Generated by Django 3.0.6 on 2020-05-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_auto_20200531_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='pair',
        ),
        migrations.DeleteModel(
            name='MyData',
        ),
        migrations.DeleteModel(
            name='MyRank',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
