# Generated by Django 3.0.6 on 2020-05-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_data_mydata_myrank_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='pair',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='MyData',
        ),
        migrations.DeleteModel(
            name='MyRank',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
