# Generated by Django 3.0.6 on 2020-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_data_mydata_myrank_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='F', max_length=1)),
                ('age', models.CharField(choices=[('u17', 'up to 17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-54', '46-54'), ('55-64', '55-64'), ('65+', '65+')], default='18-25', max_length=5)),
                ('education', models.CharField(choices=[('primary', 'Πρωτοβάθμια / Primary'), ('secondary', 'Δευτεροβάθμια / Secondary'), ('undergrad ', 'Προπτυχιακό / Undergrad '), ('BSc', 'Πτυχίο / Bachelor'), ('MSc', "Μεταπτυχιακό / Master's"), ('PhD', 'Διδακτορικό / Doctorate')], default='secondary', max_length=11)),
                ('industry', models.CharField(max_length=40)),
                ('art_experience', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=2)),
            ],
        ),
    ]
