# Generated by Django 3.0.7 on 2020-06-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_auto_20200614_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='art_experience',
            field=models.CharField(choices=[('1', '1 - Καθόλου / Irrelevant'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - Μέγιστη / Best')], max_length=2),
        ),
    ]
