# Generated by Django 3.0.7 on 2020-06-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_auto_20200615_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='industry',
            new_name='sector',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(choices=[('', '-'), ('u17', 'up to 17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-54', '46-54'), ('55-64', '55-64'), ('65+', '65+')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='art_experience',
            field=models.CharField(choices=[('', '-'), ('1', '1 - Καθόλου / Irrelevant'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - Μέγιστη / Top')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('', '-'), ('primary', 'Πρωτοβάθμια / Primary'), ('secondary', 'Δευτεροβάθμια / Secondary'), ('undergrad ', 'Προπτυχιακό / Undergrad '), ('BSc', 'Πτυχίο / Bachelor'), ('MSc', "Μεταπτυχιακό / Master's"), ('PhD', 'Διδακτορικό / Doctorate')], max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', '-'), ('M', 'Άρρεν / Male'), ('F', 'Θήλυ / Female')], max_length=1),
        ),
    ]
