# Generated by Django 3.0.7 on 2020-06-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_auto_20200618_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='pair',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='MyData',
        ),
        migrations.DeleteModel(
            name='MyRank',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
