# Generated by Django 3.0.7 on 2020-06-18 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_auto_20200619_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.PositiveSmallIntegerField()),
                ('success', models.PositiveSmallIntegerField()),
                ('failure', models.PositiveSmallIntegerField()),
                ('total_score', models.FloatField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('response', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Rank',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('gender', models.CharField(choices=[('', '---'), ('M', 'Άρρεν / Male'), ('F', 'Θήλυ / Female')], max_length=1)),
                ('age', models.CharField(choices=[('', '---'), ('u17', '-17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-54', '46-54'), ('55-64', '55-64'), ('65+', '65+')], max_length=5)),
                ('education', models.CharField(choices=[('', '---'), ('primary', 'Πρωτοβάθμια / Primary'), ('secondary', 'Δευτεροβάθμια / Secondary'), ('undergrad ', 'Προπτυχιακό / Undergrad '), ('BSc', 'Πτυχίο / Bachelor'), ('MSc', "Μεταπτυχιακό / Master's"), ('PhD', 'Διδακτορικό / Doctorate')], max_length=11)),
                ('sector', models.CharField(max_length=40)),
                ('knowledge', models.CharField(choices=[('', '---'), ('1', 'Λίγο ή καθόλου / Little or no knowledge'), ('2', 'Γενική / General'), ('3', 'Αρκετή / Intermediate'), ('4', 'Προχωρημένη / Advanced'), ('5', 'Εξειδικευμένη / Specialist')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.FloatField(null=True)),
                ('filename_pri', models.CharField(blank=True, max_length=120, null=True)),
                ('filename_sec', models.CharField(blank=True, max_length=120, null=True)),
                ('xtl_pri', models.FloatField(null=True)),
                ('ytl_pri', models.FloatField(null=True)),
                ('xbr_pri', models.FloatField(null=True)),
                ('ybr_pri', models.FloatField(null=True)),
                ('xtl_sec', models.FloatField(null=True)),
                ('ytl_sec', models.FloatField(null=True)),
                ('xbr_sec', models.FloatField(null=True)),
                ('ybr_sec', models.FloatField(null=True)),
                ('countdown_per_pic', models.PositiveSmallIntegerField()),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_data', to='pages.Pair')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='MyRank',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Rank',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.user',),
        ),
    ]
