# Generated by Django 3.0.7 on 2020-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_data_mydata_myrank_myuser_rank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='knowledge',
            field=models.CharField(choices=[('', '---'), ('1', 'Λίγες ή καθόλου / Little or no knowledge'), ('2', 'Γενικές / General'), ('3', 'Αρκετές / Intermediate'), ('4', 'Προχωρημένες / Advanced'), ('5', 'Εξειδικευμένες / Specialist')], max_length=2),
        ),
    ]
