# Generated by Django 3.0.8 on 2020-07-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0061_data_mydata_myoption_mypair_myrank_mytarget_myuser_option_pair_rank_target_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='pair',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.RemoveField(
            model_name='target',
            name='pair',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='MyData',
        ),
        migrations.DeleteModel(
            name='MyOption',
        ),
        migrations.DeleteModel(
            name='MyPair',
        ),
        migrations.DeleteModel(
            name='MyRank',
        ),
        migrations.DeleteModel(
            name='MyTarget',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
