# Generated by Django 3.0.8 on 2020-07-06 06:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0062_auto_20200706_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_count', models.PositiveSmallIntegerField(default=15)),
                ('countdown_per_pic', models.PositiveSmallIntegerField(default=60)),
                ('language', models.CharField(choices=[('EL', 'EL'), ('EN', 'EN')], default='EL', max_length=2)),
                ('headline_el', models.CharField(default='Οδηγίες', max_length=25)),
                ('headline_en', models.CharField(default='Instructions', max_length=25)),
                ('instructions_el', ckeditor.fields.RichTextField(default='Χώρος εισαγωγής οδηγιών/πληροφοριών.')),
                ('instructions_en', ckeditor.fields.RichTextField(default='Put your instructions here')),
                ('footer_el', models.CharField(default='© 2020 Περικλής Περικλέους - Πανεπιστήμιο Πατρών', max_length=120)),
                ('footer_en', models.CharField(default='© 2020 Periklis Perikleous - University of Patras', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_pri_el', ckeditor.fields.RichTextField(max_length=50)),
                ('caption_pri_en', ckeditor.fields.RichTextField(max_length=50)),
                ('caption_sec_el', ckeditor.fields.RichTextField(max_length=50)),
                ('caption_sec_en', ckeditor.fields.RichTextField(max_length=50)),
                ('description_el', ckeditor.fields.RichTextField(blank=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True)),
                ('image_pri', models.ImageField(height_field='height_pri', upload_to='', width_field='width_pri')),
                ('height_pri', models.IntegerField(default=0)),
                ('width_pri', models.IntegerField(default=0)),
                ('image_sec', models.ImageField(height_field='height_sec', upload_to='', width_field='width_sec')),
                ('height_sec', models.IntegerField(default=0)),
                ('width_sec', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pairs',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.PositiveSmallIntegerField()),
                ('success', models.PositiveSmallIntegerField()),
                ('failure', models.PositiveSmallIntegerField()),
                ('total_score', models.FloatField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('response', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Rank',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('gender', models.CharField(choices=[('', '---'), ('M', 'Άρρεν / Male'), ('F', 'Θήλυ / Female')], max_length=1)),
                ('age', models.CharField(choices=[('', '---'), ('u17', '-17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-54', '46-54'), ('55-64', '55-64'), ('65+', '65+')], max_length=5)),
                ('education', models.CharField(choices=[('', '---'), ('primary', 'Πρωτοβάθμια / Primary'), ('secondary', 'Δευτεροβάθμια / Secondary'), ('undergrad ', 'Προπτυχιακό / Undergrad '), ('BSc', 'Πτυχίο / Bachelor'), ('MSc', "Μεταπτυχιακό / Master's"), ('PhD', 'Διδακτορικό / Doctorate')], max_length=11)),
                ('sector', models.CharField(max_length=40)),
                ('knowledge', models.CharField(choices=[('', '---'), ('1', 'Λίγες ή καθόλου / Little or no knowledge'), ('2', 'Γενικές / General'), ('3', 'Σχετικές / Intermediate'), ('4', 'Προχωρημένες / Advanced'), ('5', 'Ειδικές / Specialist')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pri', models.FloatField(verbose_name='x - primary')),
                ('y_pri', models.FloatField(verbose_name='y - primary')),
                ('w_pri', models.FloatField(verbose_name='width - primary')),
                ('h_pri', models.FloatField(verbose_name='height - primary')),
                ('x_sec', models.FloatField(null=True, verbose_name='x - secondary')),
                ('y_sec', models.FloatField(null=True, verbose_name='y - secondary')),
                ('w_sec', models.FloatField(null=True, verbose_name='width - secondary')),
                ('h_sec', models.FloatField(null=True, verbose_name='height - secondary')),
                ('pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pair_target', to='pages.Pair')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.FloatField(null=True)),
                ('filename_pri', models.CharField(blank=True, max_length=120, null=True)),
                ('filename_sec', models.CharField(blank=True, max_length=120, null=True)),
                ('xtl_pri', models.FloatField(null=True)),
                ('ytl_pri', models.FloatField(null=True)),
                ('xbr_pri', models.FloatField(null=True)),
                ('ybr_pri', models.FloatField(null=True)),
                ('xtl_sec', models.FloatField(null=True)),
                ('ytl_sec', models.FloatField(null=True)),
                ('xbr_sec', models.FloatField(null=True)),
                ('ybr_sec', models.FloatField(null=True)),
                ('countdown_per_pic', models.PositiveSmallIntegerField()),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_data', to='pages.Pair')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='MyOption',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.option',),
        ),
        migrations.CreateModel(
            name='MyPair',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Pairs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.pair',),
        ),
        migrations.CreateModel(
            name='MyRank',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Rank',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='MyTarget',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Targets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.target',),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'verbose_name_plural': '~ Import/Export Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.user',),
        ),
    ]
