# Generated by Django 3.0.8 on 2020-11-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_data_mydata_myoption_mypair_myrank_mytarget_myuser_option_pair_rank_target_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='MyRank',
        ),
    ]
