# Generated by Django 3.0.8 on 2020-11-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0065_myrank_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='total_score',
        ),
    ]
